package cz.smarteon.loxmcp.loxonedocs

import cz.smarteon.loxmcp.readResourceBytes
import io.github.oshai.kotlinlogging.KotlinLogging
import io.ktor.client.HttpClient
import io.ktor.client.plugins.HttpTimeout
import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText
import io.ktor.http.decodeURLPart
import io.ktor.http.encodeURLPathPart
import io.ktor.http.isSuccess
import io.modelcontextprotocol.kotlin.sdk.types.ReadResourceResult
import io.modelcontextprotocol.kotlin.sdk.types.TextResourceContents
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray

private val logger = KotlinLogging.logger {}

/**
 * Provides access to pre-parsed Loxone documentation data.
 *
 * Documentation is loaded from versioned JSON files generated by CI and stored in
 * the repository. Files are named `structure-file-{version}.json` and served via
 * GitHub raw content.
 *
 * The document is split into two top-level collections:
 * - **generalSections**: Non-control sections (General Info, rooms, globalStates, etc.)
 * - **controls**: Control type docs with details, states, and commands
 *
 * Version selection logic based on Miniserver firmware version:
 * - If the Miniserver version is lower than all available versions, use the lowest
 * - If the Miniserver version is higher than all available versions, use the highest
 * - Otherwise use the highest available version not exceeding the Miniserver version
 */
object LoxoneDocsProvider {

    private const val GITHUB_RAW_BASE_URL =
        "https://raw.githubusercontent.com/Smarteon/lox-mcp/main/loxone-docs"
    private const val VERSIONS_INDEX_FILE = "versions.json"
    private const val DOWNLOAD_TIMEOUT_SECONDS = 15L
    internal const val CLASSPATH_PREFIX = "/loxone-docs"

    private val json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
    }

    private var cachedFile: ParsedStructureFile? = null

    /**
     * Gets all general (non-control) documentation sections for the given Miniserver version.
     */
    fun getGeneralSections(miniserverVersion: String? = null): List<StructureSection> {
        val file = getParsedFile(miniserverVersion) ?: return emptyList()
        return file.generalSections
    }

    /**
     * Gets all control type documentation for the given Miniserver version.
     */
    fun getControls(miniserverVersion: String? = null): List<StructureControl> {
        val file = getParsedFile(miniserverVersion) ?: return emptyList()
        return file.controls
    }

    /**
     * Returns all controls flattened to a single list, including nested subsections.
     */
    fun getAllControlsFlat(miniserverVersion: String? = null): List<StructureControl> {
        val result = mutableListOf<StructureControl>()
        fun collect(controls: List<StructureControl>) {
            for (c in controls) {
                result.add(c)
                collect(c.subsections)
            }
        }
        collect(getControls(miniserverVersion))
        return result
    }

    /**
     * Finds a control type by name (case-insensitive), searching the full tree.
     */
    fun findControl(name: String, miniserverVersion: String? = null): StructureControl? =
        getAllControlsFlat(miniserverVersion).find { it.name.equals(name, ignoreCase = true) }

    /**
     * Finds a general section by name (case-insensitive).
     */
    fun findGeneralSection(name: String, miniserverVersion: String? = null): StructureSection? {
        fun search(sections: List<StructureSection>): StructureSection? {
            for (s in sections) {
                if (s.name.equals(name, ignoreCase = true)) return s
                search(s.subsections)?.let { return it }
            }
            return null
        }
        return search(getGeneralSections(miniserverVersion))
    }

    /**
     * Clears the cache, forcing a reload on next access.
     */
    fun clearCache() {
        cachedFile = null
        logger.info { "Loxone documentation cache cleared" }
    }

    /**
     * Resolves which docs version to use based on the Miniserver firmware version.
     */
    internal fun resolveDocsVersion(miniserverVersion: String?): String {
        val available = getAvailableVersions().sorted()
        val msVersion = miniserverVersion?.let { DocsVersion.parse(it) }
        val resolved = when {
            available.isEmpty() -> {
                logger.warn { "No available docs versions found" }
                return ""
            }
            msVersion == null -> available.last()
            msVersion <= available.first() -> available.first()
            msVersion >= available.last() -> available.last()
            else -> available.filter { it <= msVersion }.max()
        }
        logger.info { "Resolved docs version for Miniserver $miniserverVersion: $resolved" }
        return resolved.toString()
    }

    /**
     * Gets the list of available docs versions from the versions index.
     * Tries classpath first, then GitHub.
     */
    internal fun getAvailableVersions(): List<DocsVersion> {
        val classpathVersions = loadVersionsFromClasspath()
        if (classpathVersions.isNotEmpty()) return classpathVersions
        return loadVersionsFromGitHub()
    }

    private fun loadVersionsFromClasspath(): List<DocsVersion> {
        return try {
            val bytes = readResourceBytes("$CLASSPATH_PREFIX/$VERSIONS_INDEX_FILE")
            if (bytes != null) {
                parseVersionsIndex(bytes.decodeToString())
            } else {
                emptyList()
            }
        } catch (e: Exception) {
            logger.debug(e) { "Could not load versions index from classpath" }
            emptyList()
        }
    }

    private fun loadVersionsFromGitHub(): List<DocsVersion> {
        return try {
            val content = downloadFromUrl("$GITHUB_RAW_BASE_URL/$VERSIONS_INDEX_FILE")
            if (content != null) parseVersionsIndex(content) else emptyList()
        } catch (e: Exception) {
            logger.debug(e) { "Could not load versions index from GitHub" }
            emptyList()
        }
    }

    private fun parseVersionsIndex(content: String): List<DocsVersion> =
        json.decodeFromString<List<String>>(content).mapNotNull { DocsVersion.parse(it) }

    private fun getParsedFile(miniserverVersion: String?): ParsedStructureFile? {
        val targetVersion = resolveDocsVersion(miniserverVersion)
        val cached = cachedFile
        if (cached != null && cached.version == targetVersion) {
            return cached
        }
        return loadParsedFile(targetVersion)?.also { cachedFile = it }
    }

    private fun loadParsedFile(version: String): ParsedStructureFile? {
        if (version.isBlank()) return null
        val fileName = "structure-file-$version.json"

        try {
            val bytes = readResourceBytes("$CLASSPATH_PREFIX/$fileName")
            if (bytes != null) {
                val content = bytes.decodeToString()
                val file = json.decodeFromString<ParsedStructureFile>(content)
                logger.info {
                    "Loaded docs v${file.version} from classpath " +
                        "(${file.generalSectionCount} general, ${file.controlCount} controls)"
                }
                return file
            }
        } catch (e: Exception) {
            logger.warn(e) { "Failed to load docs from classpath: $fileName" }
        }

        try {
            val content = downloadFromUrl("$GITHUB_RAW_BASE_URL/$fileName")
            if (content != null) {
                val file = json.decodeFromString<ParsedStructureFile>(content)
                logger.info {
                    "Loaded docs v${file.version} from GitHub " +
                        "(${file.generalSectionCount} general, ${file.controlCount} controls)"
                }
                return file
            }
        } catch (e: Exception) {
            logger.error(e) { "Failed to load docs from GitHub: $fileName" }
        }

        logger.error { "Could not load Loxone documentation for version $version" }
        return null
    }

    private val httpClient by lazy {
        HttpClient {
            install(HttpTimeout) {
                requestTimeoutMillis = DOWNLOAD_TIMEOUT_SECONDS * 1_000
                connectTimeoutMillis = DOWNLOAD_TIMEOUT_SECONDS * 1_000
            }
        }
    }

    private fun downloadFromUrl(url: String): String? {
        return try {
            runBlocking(Dispatchers.Default) {
                withTimeout(DOWNLOAD_TIMEOUT_SECONDS * 1_000) {
                    val response = httpClient.get(url)
                    if (response.status.isSuccess()) response.bodyAsText() else null
                }
            }
        } catch (e: Exception) {
            logger.debug(e) { "Failed to download from $url" }
            null
        }
    }

    /**
     * Handles the docs Table of Contents request.
     *
     * Returns a structured TOC showing:
     * - General sections (rooms, globalStates, etc.) under `generalSections`
     * - Control types under `controls`
     *
     * Each entry is a "clickable" item with a `detailUri` pointing to `loxone://docs/topic/{name}`.
     */
    fun handleDocsToc(uri: String, miniserverVersion: String? = null): ReadResourceResult {
        val file = getParsedFile(miniserverVersion)
            ?: return errorResult(uri, "Failed to load Loxone documentation")

        fun sectionEntry(section: StructureSection): JsonObject =
            buildJsonObject {
                put("name", section.name)
                if (section.description.isNotBlank()) put("description", section.description)
                put("type", "generalSection")
                put("detailUri", "loxone://docs/topic/${section.name.encodeURLPathPart()}")
                if (section.subsections.isNotEmpty()) {
                    putJsonArray("subsections") { section.subsections.forEach { add(sectionEntry(it)) } }
                }
            }

        fun controlEntry(control: StructureControl): JsonObject =
            buildJsonObject {
                put("name", control.name)
                if (control.description.isNotBlank()) put("description", control.description)
                put("type", "control")
                put("detailUri", "loxone://docs/topic/${control.name.encodeURLPathPart()}")
                put("detailsCount", control.details.size)
                put("statesCount", control.states.size)
                put("commandsCount", control.commands.size)
                if (control.subsections.isNotEmpty()) {
                    putJsonArray("subsections") { control.subsections.forEach { add(controlEntry(it)) } }
                }
            }

        val toc = buildJsonObject {
            put("version", file.version)
            put(
                "hint",
                "Use loxone://docs/topic/{name} to read details for any item. " +
                    "Use loxone://docs/controls for a flat list of all control types."
            )
            putJsonArray("generalSections") { file.generalSections.forEach { add(sectionEntry(it)) } }
            putJsonArray("controls") { file.controls.forEach { add(controlEntry(it)) } }
        }

        return successResult(uri, json.encodeToString(JsonObject.serializer(), toc))
    }

    /**
     * Handles the docs controls list request.
     *
     * Returns a flat list of all control types (including nested subsections),
     * each with a `detailUri` for easy navigation.
     */
    fun handleDocsControlsList(uri: String, miniserverVersion: String? = null): ReadResourceResult {
        val controls = getAllControlsFlat(miniserverVersion)
        if (controls.isEmpty()) {
            return errorResult(uri, "Failed to load Loxone documentation or no controls found")
        }
        val list = buildJsonArray {
            controls.forEach { control ->
                add(buildJsonObject {
                    put("name", control.name)
                    if (control.description.isNotBlank()) put("description", control.description)
                    put("detailsCount", control.details.size)
                    put("statesCount", control.states.size)
                    put("commandsCount", control.commands.size)
                put("detailUri", "loxone://docs/topic/${control.name.encodeURLPathPart()}")
                })
            }
        }
        return successResult(uri, json.encodeToString(JsonArray.serializer(), list))
    }

    /**
     * Handles a topic detail request — works for both control types and general sections.
     *
     * Tries controls first (case-insensitive), then general sections.
     */
    fun handleDocsTopic(uri: String, miniserverVersion: String? = null): ReadResourceResult {
        val topicName = uri.substringAfter("docs/topic/").trim().decodeURLPart()
        if (topicName.isBlank()) {
            return errorResult(uri, "Topic name not found in URI")
        }

        findControl(topicName, miniserverVersion)?.let { control ->
            return successResult(uri, json.encodeToString(StructureControl.serializer(), control))
        }

        findGeneralSection(topicName, miniserverVersion)?.let { section ->
            return successResult(uri, json.encodeToString(StructureSection.serializer(), section))
        }

        return errorResult(
            uri,
            "Topic '$topicName' not found. Use loxone://docs to browse available topics."
        )
    }

    private fun successResult(uri: String, content: String) = ReadResourceResult(
        contents = listOf(TextResourceContents(uri = uri, mimeType = "application/json", text = content))
    )

    private fun errorResult(uri: String, message: String) = ReadResourceResult(
        contents = listOf(TextResourceContents(uri = uri, mimeType = "text/plain", text = "Error: $message"))
    )
}

/**
 * Represents a Loxone documentation version in X.Y format.
 */
data class DocsVersion(val major: Int, val minor: Int) : Comparable<DocsVersion> {

    override fun compareTo(other: DocsVersion): Int {
        val majorCmp = major.compareTo(other.major)
        return if (majorCmp != 0) majorCmp else minor.compareTo(other.minor)
    }

    override fun toString(): String = "$major.$minor"

    companion object {
        fun parse(version: String): DocsVersion? {
            val parts = version.split(".")
            if (parts.size < 2) return null
            val major = parts[0].toIntOrNull() ?: return null
            val minor = parts[1].toIntOrNull() ?: return null
            return DocsVersion(major, minor)
        }
    }
}
