package cz.smarteon.loxmcp.loxonedocs

import kotlinx.serialization.Serializable

/**
 * Wrapper for pre-parsed Loxone documentation with metadata.
 * Generated by the CI pipeline and stored as JSON in the repository.
 *
 * @property version Loxone documentation version (X.Y format, e.g., "16.0")
 * @property sourceUrl URL of the source PDF that was parsed
 * @property parsedAt ISO-8601 timestamp of when the parsing occurred
 * @property generalSectionCount Number of general (non-control) sections
 * @property controlCount Number of control type sections
 * @property generalSections General info sections (rooms, cats, globalStates, etc.)
 * @property controls Control type sections (Switch, Dimmer, Jalousie, etc.)
 */
@Serializable
data class ParsedStructureFile(
    val version: String,
    val sourceUrl: String,
    val parsedAt: String,
    val generalSectionCount: Int,
    val controlCount: Int,
    val generalSections: List<StructureSection>,
    val controls: List<StructureControl>
)

/**
 * A general (non-control) section of the Loxone Structure File documentation.
 *
 * Represents top-level chapters like "General Info", "rooms", "globalStates", etc.
 */
@Serializable
data class StructureSection(
    val name: String,
    val description: String = "",
    val fields: List<StructureField> = emptyList(),
    val subsections: List<StructureSection> = emptyList()
)

/**
 * A control type section from the Loxone Structure File documentation.
 *
 * Uses the PDF's own terminology: Details, States, Commands.
 *
 * @property name Control type name (e.g., "Switch", "Dimmer", "Jalousie")
 * @property description General description of the control
 * @property coveredConfigItems Which Loxone Config items this control covers
 * @property details Configuration details (read-only properties set in Loxone Config)
 * @property states Runtime states that change over time
 * @property commands Commands that can be sent to control the device
 * @property subsections Nested sub-control types (e.g., "BMW Wallbox specific" under "CarCharger")
 */
@Serializable
data class StructureControl(
    val name: String,
    val description: String = "",
    val coveredConfigItems: String? = null,
    val details: List<StructureField> = emptyList(),
    val states: List<StructureField> = emptyList(),
    val commands: List<StructureCommand> = emptyList(),
    val subsections: List<StructureControl> = emptyList()
)

/**
 * A state, detail, or configuration field documented for a section.
 */
@Serializable
data class StructureField(
    val name: String,
    val description: String,
    val enumValues: Map<String, String>? = null
)

/**
 * A command that can be sent to a control.
 */
@Serializable
data class StructureCommand(
    val name: String,
    val description: String
)

/**
 * Summary of a control for list views.
 */
@Serializable
data class StructureControlSummary(
    val name: String,
    val detailsCount: Int,
    val statesCount: Int,
    val commandsCount: Int,
    val subsectionsCount: Int
)
